name: contextstring display
on: 
push
jobs:
dump_context_tolog
runs-on: unbuntu-latest
steps:
-name: dump github context
env:
GITHUB_CONTEXT:${{tojason(github)}}
run:
echo "$GITHUB_CONTEXT"
-name: dump job context
env: 
JOB_CONTEXT:${{tojason(job)}}
run:
echo "$JOB_CONTEXT"
-name: dump step context
env: 
STEP_CONTEXT:${{tojason(steps)}}
run:
echo "$STEP_CONTEXT"
-name: dump runner context
env: 
RUNNER_CONTEXT:${{tojason(runner)}}
run:
echo "$RUNNER_CONTEXT"
-name: dump stratergy context
env: 
STRAGERTY_CONTEXT:${{tojason(stratergy)}}
run:
echo "$JOB_CONTEXT"
-name: dump matrix context
env: 
MATRIX_CONTEXT:${{tojason(matrix)}}
run:
echo "$MATRIX_CONTEXT"
